### PR TITLE
fix!: `addMethod` now passes errors it receives; added test

### PR DESCRIPTION
**Pull request by ryleelyman**
just a small fix + a test for `class.addMethod`

### CODE REVIEW

**Comment by ryleelyman** [comment]
actually, rather than returning a `bool`, since we're already returning an error if `createFnSignature` fails, maybe it would be good to convert a `false` result to `c.class_addMethod` into a zig error; just did that.

**Comment by mitchellh** [comment]
> actually, rather than returning a `bool`, since we're already returning an error if `createFnSignature` fails, maybe it would be good to convert a `false` result to `c.class_addMethod` into a zig error; just did that.

Totally on board with this, but we have so many other methods that return bool that for now I think ill revert this and we can do them all in bulk. Might want to just use a simple `error{ObjcOpeationFailed}` or something rather than a per-method error so we don't make a huge error set, too.

**Comment by mitchellh** [comment]
Alright, no functional changes, but I batched in merging #1, modifying it, and I added a `comptimeEncode` function that produces a perfectly-sized comptime string for a type encoding, so there is no runtime encoding cost and the encoding is just in the binary rodata!

**Comment by mitchellh** [comment]
I also noticed for some reason our macOS SDK in CI uses i8 return values for bools and locally it uses stdbool. I added a stupid little `boolResult` function that comptime figures that out so CI will pass. It has no runtime cost but its source code noise...

**Comment by ryleelyman** [comment]
yeah i just noticed that when updating to macOS 14 that the BOOL type switched… thanks for including a little something for that!

**Pull request merged**
